name: 'DigitalOcean kubectl'
author: Arnob Almazee
description: DigitalOcean kubectl in a Github Action
branding:
  color: 'green'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/arn-ob/do-kubectl-action:latest'
inputs:
  do_access_token:
    description: DigitalOcean access token for accessing the doctl. 
    required: true
  do_cluster_certificate:
    description: DigitalOcean cluster certificate for accessing the kubectl. 
    required: true
  do_deployment_name:
    description: kubectl deployment name. 
    required: true
  do_container_name:
    description: kubectl container name. 
    required: true
  do_image_tag:
    description: kubectl image and tag. 
    required: true
  stdin:
    description: File to read and pass as stdin to kubectl
    required: false
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
outputs:
  kubectl-out:
    description: The output of the kubectl command