name: 'DigitalOcean kubectl'
author: Arnob Almazee
description: DigitalOcean kubectl in a Github Action
branding:
  color: 'green'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/arn-ob/do-kubectl-action:latest'
inputs:
  do_k8s_token:
    description: DigitalOcean access token for accessing the doctl.
    required: true
  stdin:
    description: File to read and pass as stdin to kubectl
    required: false
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
outputs:
  kubectl-out:
    description: The output of the kubectl command