name: 'DigitalOcean kubectl'
author: arn-ob
description: An action allowing you to integrate with DigitalOcean via kubectl in a Github Action, easily...
branding:
  color: 'white'
  icon: 'command'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/arn-ob/do-kubectl-action:latest'
inputs:
  eks_role_arn:
    description: EKS role arn that allow access eks cluster (Mostly happen when you create your cluster with CDK).
    required: false
  stdin:
    description: File to read and pass as stdin to kubectl
    required: false
  args:
    description: The arguments that you want to pass through to the kubectl command
    required: true
outputs:
  kubectl-out:
    description: The output of the kubectl command